name: Deploy


on:
  push:
    branches:
    - **

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION_ID }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.1.0
  
        - name: Terraform Init
          run: terraform init
  
        - name: Terraform Format
          run: terraform fmt -check
        
        - name: Terraform Validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan
  
        - name: Terraform Apply
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve